import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import LoignBtn from "./components/LoginBtn/LoginBtn";
import { getServerSession } from "next-auth";
import { authOptions } from "@/pages/api/auth/[...nextauth]";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "NextJS앱",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  let session = await getServerSession(authOptions);

  return (
    <html lang="ko">
      <body>
        <div className="navbar">
            <Link href="/" className="logo">Board</Link>
            <Link href="/list">list</Link>
            <Link href="/write">write</Link>
            <LoignBtn login={session}/>
        </div>
        {children}
        </body>
    </html>
  );
}


// 소셔로그인 설정
// npm installl next-auth
// pages폴더 안에 api폴더 안에 auth폴더 생성하고
// [...nextauth].js 파일을 생성
// [] : dynamic route(동적 URL) : 각 소셜로그인에서 제공하는 경로를 넣을 것임(구글, 깃허브, 페이스북 등.. 다 다르게 제공)